version: '3'
networks:
    db:
    web:
    fila:
services:
    db:
        image: postgres:9.6
        environment: 
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            #- dados:/var/lib/postgresql/data
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            # Definir o nome do diretório para backup
            #- ./pg-banco:/var/lib/postgresql/data
        networks:
            - db
    web: 
        image: nginx:1.13
        volumes:
             #Site
             - ./web:/usr/share/nginx/html
             #Proxy Reverso
             - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - web
        depends_on:
            - app
    app:
        image: python:3.7.2
        volumes: 
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        networks:
            - db
            - web
            - fila
        depends_on:
            - db
            - fila
        environment: 
            - DB_NAME=falso
    fila:
        image: redis:3.2
        networks:
            - fila
    atendente:
        #image: python:3.7.2
        build: atendente
        volumes:
            - ./atendente:/atendente
        working_dir: /atendente
        #command: bash ./atendente.sh
        command: atendente.py
        networks:
            - fila
        depends_on: 
            - fila




            

